<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GenerateProgramFile>false</GenerateProgramFile>
    </PropertyGroup>

    <ItemGroup>

        <ProjectReference Include="..\NexaCommerce.Modules.CartModule.Application\NexaCommerce.Modules.CartModule.Application.csproj"/>

        <ProjectReference Include="..\NexaCommerce.Modules.CartModule.Infrastructure\NexaCommerce.Modules.CartModule.Infrastructure.csproj"/>

    </ItemGroup>

</Project>