<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
    <ItemGroup>

        <ProjectReference Include="..\..\..\BuildingBlocks\NexaCommerce.SharedKernel\NexaCommerce.SharedKernel.csproj" />

        <ProjectReference Include="..\..\..\BuildingBlocks\NexaCommerce.Common\NexaCommerce.Common.csproj" />

        <ProjectReference Include="..\..\Inventory\NexaCommerce.Modules.Inventory.Application\NexaCommerce.Modules.Inventory.Application.csproj" />

        <ProjectReference Include="..\NexaCommerce.Modules.OrderModule.Domain\NexaCommerce.Modules.OrderModule.Domain.csproj" />

    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="MediatR" />
        <PackageReference Include="FluentValidation" />
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    </ItemGroup>
</Project>
