<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\NexaCommerce.Modules.CartModule.Domain\NexaCommerce.Modules.CartModule.Domain.csproj" />
    <ProjectReference Include="..\..\Inventory\NexaCommerce.Modules.Inventory.Application\NexaCommerce.Modules.Inventory.Application.csproj" />
    <ProjectReference Include="..\..\Catalog\NexaCommerce.Modules.Catalog.Application\NexaCommerce.Modules.Catalog.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="MediatR" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
