<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\NexaCommerce.Modules.OrderModule.Application\NexaCommerce.Modules.OrderModule.Application.csproj" />
      <ProjectReference Include="..\NexaCommerce.Modules.OrderModule.Infrastructure\NexaCommerce.Modules.OrderModule.Infrastructure.csproj" />
    </ItemGroup>

</Project>